version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: survey-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: survey
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.0
    container_name: survey-redis
    ports:
      - "6379:6379"

volumes:
  mysql-data:
    